Controllers/DepartmanController.cs
using PersonelMVCUI.Models.EntityFramework;
using PersonelMVCUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonelMVCUI.Controllers
{
    
    [Authorize(Roles = "A,U")]
    public class DepartmanController : Controller
    {
        DepartmanMVCEntities6 db = new DepartmanMVCEntities6();

        [HandleError]
        public ActionResult Index()
        {
            var model = db.Departman.ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Yeni()
        {
            return View("DepartmanForm", new Departman());
        }

        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Departman departman)
        {
            if (!ModelState.IsValid)
            {
                return View("DepartmanForm");
            }
            MesajViewModel model = new MesajViewModel();
            if (departman.Id == 0)
            {
                db.Departman.Add(departman);
                model.Mesaj = departman.Ad + " başarıyla eklendi...";
            }
            else
            {
                var guncellenecekDepartman = db.Departman.Find(departman.Id);
                if(guncellenecekDepartman == null)
                {
                    return HttpNotFound();
                }
                guncellenecekDepartman.Ad = departman.Ad;
                model.Mesaj = departman.Ad + " başarıyla güncellendi...";
            }
            db.SaveChanges();
            model.Status = true;
            model.LinkText = "Departman Listesi";
            model.Url = "/Departman";
            return PartialView("_Mesaj",model);
            
        }

        public ActionResult Guncelle(int id)
        {
            var model = db.Departman.Find(id);
            if (model == null)
                return HttpNotFound();
            return View("DepartmanForm", model);
        }

        public ActionResult Sil(int id)
        {
            var silinecekDepartman = db.Departman.Find(id);
            if (silinecekDepartman == null)
                return HttpNotFound();
            db.Departman.Remove(silinecekDepartman);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/PersonelController.cs
using PersonelMVCUI.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PersonelMVCUI.ViewModels;

namespace PersonelMVCUI.Controllers
{
    [Authorize(Roles = "A,U")]
    public class PersonelController : Controller
    {
        DepartmanMVCEntities6 db = new DepartmanMVCEntities6();

        [OutputCache(Duration =30)]
        public ActionResult Index()
        {
            var model = db.Personel.Include(x => x.Departman).ToList();
            return View(model);
        }

        
        public ActionResult Yeni()
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel=new Personel()
            };
            return View("PersonelForm", model);
        }

        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Personel personel)
        {
            if (!ModelState.IsValid)
            {
                var model = new PersonelFormViewModel()
                {
                    Departmanlar = db.Departman.ToList(),
                    Personel = personel
                };
                return View("PersonelForm", model);
            }
            if (personel.Id == 0)
            {
                db.Personel.Add(personel);
            }
            else
            {
                db.Entry(personel).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Guncelle(int id)
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = db.Personel.Find(id)
            };
            return View("PersonelForm", model);
        }
        public ActionResult Sil(int id)
        {
            var silenecekPersonel = db.Personel.Find(id);
            if(silenecekPersonel == null)
            {
                return HttpNotFound();
            }
            db.Personel.Remove(silenecekPersonel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelleriGetir(int id)
        {
            var model = db.Personel.Where(x => x.DepartmanId == id).ToList();
            return PartialView(model);
        }

        public int? ToplamMaas()
        {
            return db.Personel.Sum(x => x.Maas);
        }
    }
}

Views/Departman/DepartmanForm.cshtml
@model PersonelMVCUI.Models.EntityFramework.Departman
@{
    ViewBag.Title = "Yeni";
}
<div id="mesaj">

</div>
@using (Ajax.BeginForm("Kaydet", "Departman", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "mesaj" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Ad)
        @Html.TextBoxFor(m => m.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Ad)
    </div>
    @Html.HiddenFor(m => m.Id)
    <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-save"></i></button>
}
@section scripts
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Views/Departman/Index.cshtml
@using PersonelMVCUI.Models.EntityFramework
@model List<Departman>
@{
    ViewBag.Title = "Departman";
}
<a class="btn btn-success" href="/Departman/Yeni"><i class="glyphicon glyphicon-plus"></i></a>
<h2>Departman Listesi</h2>
<table class="table table-bordered" id="tblDepartmanlar">
    <thead>
    <th>ID</th>
    <th>Ad</th>
    <th>Güncelle</th>
    <th>Sil</th>
    <th>Personeller</th>
    </thead>
    <tbody>
        @foreach (var departman in Model)
        {
            <tr>
                <td>@departman.Id</td>
                <td>@departman.Ad</td>
                <td><a href="/Departman/Guncelle/@departman.Id" class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i></a></td>
                <td><a class="btn btn-danger btnDepartmanSil" data-id="@departman.Id"><i class="glyphicon glyphicon-trash"></i></a></td>
                <td>
                    @*@Html.ActionLink("Personelleri Göster","PersonelleriGetir","Personel", new { id=departman.Id} ,new { @class="btn btn-primary"})*@
                    @Ajax.ActionLink("Personelleri Göster", "PersonelleriGetir", "Personel",
                       new { id = departman.Id },
                       new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "personelListesi" },
                       new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>
<div id="personelListesi"></div>